# Generated by Django 4.0.1 on 2022-01-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='desricao',
            new_name='descricao',
        ),
    ]
