# Generated by Django 4.0.1 on 2022-01-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_desricao_filial_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
